name: unsplash_client
description: An unofficial, platform independent client for accessing the Unsplash.com REST api.
version: 0.1.1
repository: https://github.com/blaugold/unsplash_client
issue_tracker: https://github.com/blaugold/unsplash_client/issues
homepage: https://github.com/blaugold/unsplash_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  http: ^0.12.0+4
  collection: ^1.14.12

dev_dependencies:
  effective_dart: ^1.2.0
  test: ^1.11.0
  matcher: ^0.12.6
  path: ^1.6.4
