name: unsplash_client
description: >-
  An unofficial, platform independent, client for the Unsplash API.
  Unsplash provides royalty-free images.
version: 2.1.0
repository: https://github.com/blaugold/unsplash_client
issue_tracker: https://github.com/blaugold/unsplash_client/issues
homepage: https://github.com/blaugold/unsplash_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  http: ^0.13.0
  collection: ^1.14.13
  logging: ^1.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  matcher: ^0.12.10
  path: ^1.8.0
